[2023-12-23T11:34:22.323+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.create_postgres_table scheduled__2003-01-06T00:00:00+00:00 [queued]>
[2023-12-23T11:34:22.364+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.create_postgres_table scheduled__2003-01-06T00:00:00+00:00 [queued]>
[2023-12-23T11:34:22.365+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-23T11:34:22.421+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2003-01-06 00:00:00+00:00
[2023-12-23T11:34:22.431+0000] {standard_task_runner.py:60} INFO - Started process 588 to run task
[2023-12-23T11:34:22.451+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_to_dum_raw_data_to_postgres', 'create_postgres_table', 'scheduled__2003-01-06T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dump_raw_data_to_postgres.py', '--cfg-path', '/tmp/tmp93po7uaz']
[2023-12-23T11:34:22.460+0000] {standard_task_runner.py:88} INFO - Job 75: Subtask create_postgres_table
[2023-12-23T11:34:22.621+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_to_dum_raw_data_to_postgres.create_postgres_table scheduled__2003-01-06T00:00:00+00:00 [running]> on host 3d316bc74082
[2023-12-23T11:34:22.837+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='10 academy' AIRFLOW_CTX_DAG_ID='dag_to_dum_raw_data_to_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2003-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2003-01-06T00:00:00+00:00'
[2023-12-23T11:34:22.843+0000] {sql.py:276} INFO - Executing: 
            create table if not exists raw_vehicle (
                track_id primary key,
                type VARCHAR(255),
                traveled_d FLOAT,
                avg_speed FLOAT
            )
        
[2023-12-23T11:34:22.891+0000] {base.py:83} INFO - Using connection ID 'week_two_dwh' for task execution.
[2023-12-23T11:34:23.103+0000] {base.py:83} INFO - Using connection ID 'week_two_dwh' for task execution.
[2023-12-23T11:34:23.128+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Name or service not known

[2023-12-23T11:34:23.179+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_to_dum_raw_data_to_postgres, task_id=create_postgres_table, execution_date=20030106T000000, start_date=20231223T113422, end_date=20231223T113423
[2023-12-23T11:34:23.226+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 75 for task create_postgres_table (could not translate host name "host.docker.local" to address: Name or service not known
; 588)
[2023-12-23T11:34:23.365+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-23T11:34:23.450+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
