[2023-12-23T12:05:14.773+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.create_raw_data_storing_tables scheduled__2023-12-22T00:00:00+00:00 [queued]>
[2023-12-23T12:05:14.783+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.create_raw_data_storing_tables scheduled__2023-12-22T00:00:00+00:00 [queued]>
[2023-12-23T12:05:14.784+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-23T12:05:14.817+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_raw_data_storing_tables> on 2023-12-22 00:00:00+00:00
[2023-12-23T12:05:14.822+0000] {standard_task_runner.py:60} INFO - Started process 3191 to run task
[2023-12-23T12:05:14.827+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_to_dum_raw_data_to_postgres', 'create_raw_data_storing_tables', 'scheduled__2023-12-22T00:00:00+00:00', '--job-id', '1197', '--raw', '--subdir', 'DAGS_FOLDER/dump_raw_data_to_postgres.py', '--cfg-path', '/tmp/tmpinq5ov7a']
[2023-12-23T12:05:14.828+0000] {standard_task_runner.py:88} INFO - Job 1197: Subtask create_raw_data_storing_tables
[2023-12-23T12:05:14.887+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_to_dum_raw_data_to_postgres.create_raw_data_storing_tables scheduled__2023-12-22T00:00:00+00:00 [running]> on host 3d316bc74082
[2023-12-23T12:05:14.945+0000] {abstractoperator.py:708} ERROR - Exception rendering Jinja template for task 'create_raw_data_storing_tables', field 'sql'. Template: 'sql/raw_vehicle_schema.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 700, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/raw_vehicle_schema.sql
[2023-12-23T12:05:14.949+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2335, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2466, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2878, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1248, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 700, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/raw_vehicle_schema.sql
[2023-12-23T12:05:14.961+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_to_dum_raw_data_to_postgres, task_id=create_raw_data_storing_tables, execution_date=20231222T000000, start_date=20231223T120514, end_date=20231223T120514
[2023-12-23T12:05:14.976+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1197 for task create_raw_data_storing_tables (sql/raw_vehicle_schema.sql; 3191)
[2023-12-23T12:05:14.999+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-23T12:05:15.020+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-23T16:02:04.191+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.create_raw_data_storing_tables scheduled__2023-12-22T00:00:00+00:00 [queued]>
[2023-12-23T16:02:04.203+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.create_raw_data_storing_tables scheduled__2023-12-22T00:00:00+00:00 [queued]>
[2023-12-23T16:02:04.204+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-23T16:02:04.377+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_raw_data_storing_tables> on 2023-12-22 00:00:00+00:00
[2023-12-23T16:02:04.384+0000] {standard_task_runner.py:60} INFO - Started process 245 to run task
[2023-12-23T16:02:04.389+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_to_dum_raw_data_to_postgres', 'create_raw_data_storing_tables', 'scheduled__2023-12-22T00:00:00+00:00', '--job-id', '1368', '--raw', '--subdir', 'DAGS_FOLDER/dump_raw_data_to_postgres.py', '--cfg-path', '/tmp/tmpgdh0szur']
[2023-12-23T16:02:04.393+0000] {standard_task_runner.py:88} INFO - Job 1368: Subtask create_raw_data_storing_tables
[2023-12-23T16:02:04.461+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_to_dum_raw_data_to_postgres.create_raw_data_storing_tables scheduled__2023-12-22T00:00:00+00:00 [running]> on host 417a45a22e6c
[2023-12-23T16:02:04.553+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='10 academy' AIRFLOW_CTX_DAG_ID='dag_to_dum_raw_data_to_postgres' AIRFLOW_CTX_TASK_ID='create_raw_data_storing_tables' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-22T00:00:00+00:00'
[2023-12-23T16:02:04.555+0000] {sql.py:276} INFO - Executing: create table if not exists raw_vehicle (
    track_id SERIAL PRIMARY KEY,
    type VARCHAR(255),
    traveled_d FLOAT,
    avg_speed FLOAT
);
create table if not exists raw_vehicle_trajectory(
    id SERIAL PRIMARY KEY,
    lat FLOAT,
    lon FLOAT,
    speed FLOAT,
    lon_acc FLOAT,
    lat_acc FLOAT,
    time FLOAT,
    track_id INTEGER REFERENCES raw_vehicle(track_id)
);

-- create type if not exists status_enum AS ENUM ('completed', 'failed');

create table if not exists csv_file_name(
    id  SERIAL PRIMARY KEY,
    name VARCHAR(500),
    status VARCHAR(100)
)
[2023-12-23T16:02:04.565+0000] {base.py:83} INFO - Using connection ID 'week_two_dwh' for task execution.
[2023-12-23T16:02:04.576+0000] {base.py:83} INFO - Using connection ID 'week_two_dwh' for task execution.
[2023-12-23T16:02:04.589+0000] {sql.py:432} INFO - Running statement: create table if not exists raw_vehicle (
    track_id SERIAL PRIMARY KEY,
    type VARCHAR(255),
    traveled_d FLOAT,
    avg_speed FLOAT
);
create table if not exists raw_vehicle_trajectory(
    id SERIAL PRIMARY KEY,
    lat FLOAT,
    lon FLOAT,
    speed FLOAT,
    lon_acc FLOAT,
    lat_acc FLOAT,
    time FLOAT,
    track_id INTEGER REFERENCES raw_vehicle(track_id)
);

-- create type if not exists status_enum AS ENUM ('completed', 'failed');

create table if not exists csv_file_name(
    id  SERIAL PRIMARY KEY,
    name VARCHAR(500),
    status VARCHAR(100)
), parameters: None
[2023-12-23T16:02:04.602+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_to_dum_raw_data_to_postgres, task_id=create_raw_data_storing_tables, execution_date=20231222T000000, start_date=20231223T160204, end_date=20231223T160204
[2023-12-23T16:02:04.644+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-23T16:02:04.673+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
